gocq:
  qq: 12345 #这里填写你的QQ号
  verifyKey: "" #这里填写你的gocq的verifyKey (未支持)
  http: "http://127.0.0.1:5700/" #gocq的http地址
  rhttp: 8000 #gocq反向http的端口设置
default: bingChat #默认聊天机器人
responseTimeout: 25 #聊天机器人响应超时时间 (未支持)
responseText:
  ping: 我在呢，我一直都在
  nullText: 说不出来了o(╥﹏╥)o
  tooFast: 太快了，要溢出来了~ ❤
  error: 太坏了~已经溢出来了 >_<
  moduleStatus: "{}还活着捏~"
caiyunToken: sdjbkgdjk #这里填写你的彩云天气token
at: true #是否开启at
slash: true #是否开启斜杠命令
