email: a@b.c # this is a fake email, you need to get your own email from openai.com
password: Adjgg # this is a fake password, you need to get your own password from openai.com
sessionToken: dsfhfjgj # this is a fake token, you need to get your own token from openai.com
temperature: 0.5
proxy: http://192.168.10.76:1077
paid: "False"
insecureAuth: "False"
api_key: fjhgddgjk # this is a fake token, you need to get your own token from openai.com
access_token: fhfjdjjg # this is a fake token, you need to get your own token from openai.com
